### ISSUE TITLE
FF of bam files

### ISSUE THREAD

**Issue by aref-alikhani** [PriitPaluoja/FetalFraction#1]
Hi Dear Priit,
I've got some maternal NIPT bam files, how can I analyse them using your package?
Would you please provide a step by step workflow?

Best regards,
Aref

**Comment by PriitPaluoja** [comment]
Dear Lucas,

The repository holds the source code used for the analysis in the thesis (https://comserv.cs.ut.ee/ati_thesis/datasheet.php?language=en). The aim of this thesis was to find and ‘calibrate’ computational methodology for estimating the proportion of cell-free fetal DNA (FF) in pregnant women’s blood sample. The SeqFF is not included as it is from another publication (see the supplementary of the PMID: 25967380).   Do estimate FF with source code available in this repository, please consult with the thesis.

All the best,
Priit Paluoja
